services:
  app_backend:
    build: .
    container_name: agrix_backend
    restart: unless-stopped
    ports:
      - 8080:8080
    environment:
      MYSQL_HOST: database
    depends_on:
      database:
        condition: service_healthy


  database:
    image: mysql:8.0.32
    container_name: agrix_database
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 10s
      retries: 5